name: 'Print'
description: 'Print the file'
inputs:
  file:  
    description: 'file to print'
    required: true

outputs:
  file_name: 
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'dist/index.js'
